### ISSUE TITLE
Is this repo ok?

### ISSUE THREAD

**Issue by ChrisLundquist** [ChrisLundquist/hubot-shell#1]
I needed this functionality and based it on some familiar code form GitHub.
In my mind, this is a missing piece of chatops that has never been exposed directly.
My hope is that we can move this over to the hubot-scripts org if GitHub is ok with this.
Naturally, we'll need a readme and all that.

If things are not ok here, feel free to delete this repo via admin tools.

/cc @technicalpickles

**Comment by technicalpickles** [comment]
Was actually working with @samlambert on it. By 'working with' I mean he did the extraction, and I was going to do the documentation and stuff. He was able to extract the coffeescript bits and also the basic shell framework, so it's a bit more advanced than this.

I'd rather open source it from github or the hubot-scripts org. I can see about adding you to it.

I wouldn't ask you to delete it, but I would ask you to delete the package.json at least so as to not use the hubot-shell npm name.

**Comment by ChrisLundquist** [comment]
Awesome! Yeah, this was my brief attempt at making something generic.

I look forward to seeing that!

:beers:
